"""Build the Hugging Face Space page from the project page's demo section.

The Space shows the same demo as https://openvlharness.github.io/#playground: the demo markup is
copied from index.html, with the same static/js/demo.js, stylesheet, icons, sample data and sample
images. The page also carries the demo server URL. Both the Space and the project page read it at
load time (demo.js looks for the first trycloudflare.com URL in the Space page), so rebuild and
upload whenever the tunnel URL changes:

  python scripts/build_space.py https://<name>.trycloudflare.com out/space
  # then upload out/space to the Space (static SDK), replacing its files
"""
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROJECT_PAGE = "https://openvlharness.github.io/"

README = """---
title: OpenVLHarness Demo
emoji: 🔍
colorFrom: indigo
colorTo: blue
sdk: static
pinned: false
short_description: Visual tool-use agent on your own model
---

Interactive demo of [OpenVLHarness](https://openvlharness.github.io/): ask questions about images
with your own model (OpenAI, or an OpenAI-compatible endpoint with tool calling). The agent loop
and perception tools run on our lab server. This page is generated by `scripts/build_space.py` in
the project page repository.
"""

EXTRA_SCRIPT = """<script>
  // The parts of main.js this page needs: show revealed blocks, close the image lightbox, theme switch.
  document.querySelectorAll('.reveal').forEach(function (e) { e.classList.add('in'); });
  var lb = document.getElementById('lightbox');
  lb.addEventListener('click', function () { lb.hidden = true; });
  document.addEventListener('keydown', function (e) { if (e.key === 'Escape') lb.hidden = true; });
  var themeBtn = document.getElementById('themeBtn');
  function syncTheme() { themeBtn.setAttribute('aria-checked', document.documentElement.getAttribute('data-theme') === 'dark'); }
  syncTheme();
  themeBtn.addEventListener('click', function () {
    var next = document.documentElement.getAttribute('data-theme') === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    try { localStorage.setItem('ovh-theme', next); } catch (e) {}
    syncTheme();
  });
</script>"""


def between(text, start, end):
    """Return text from the first `start` through the first following `end` (inclusive)."""
    i = text.index(start)
    j = text.index(end, i) + len(end)
    return text[i:j]


def build(server_url, out):
    if not re.fullmatch(r"https://[a-z0-9-]+\.trycloudflare\.com", server_url):
        raise SystemExit("server URL must look like https://<name>.trycloudflare.com")
    page = (ROOT / "index.html").read_text()
    head_links = "\n".join(line for line in page.splitlines()
                           if line.strip().startswith(('<link rel="icon"', '<link rel="preconnect"', '<link href="https://fonts')))
    theme_script = between(page, "<script>\n    // dark by default", "</script>")
    sprite = between(page, '<svg width="0" height="0"', "</svg>")
    nav = between(page, '<nav class="nav">', "</nav>")
    links = between(nav, '<div class="nav-links">', "</div>")
    nav = nav.replace(links, f'<div class="nav-links">\n      <a href="{PROJECT_PAGE}" target="_blank" rel="noopener">Project page</a>\n'
                             f'      <a href="{PROJECT_PAGE}#results" target="_blank" rel="noopener">Results</a>\n    </div>')
    nav = nav.replace('<a class="brand" href="#top">', f'<a class="brand" href="{PROJECT_PAGE}" target="_blank" rel="noopener">')
    demo = between(page, '<section class="block" id="playground">', "</section>")
    lightbox = between(page, '<div class="lightbox" id="lightbox"', "</div>")
    versions = {name: re.search(rf'static/js/{name}\.js\?v=(\d+)', page).group(1) for name in ("examples", "demo")}
    css_version = re.search(r'static/css/style\.css\?v=(\d+)', page).group(1)

    html = f"""<!doctype html>
<html lang="en" data-theme="dark">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>OpenVLHarness demo</title>
  <meta name="description" content="Interactive demo of OpenVLHarness: a visual tool-use agent running on your own model.">
  <!-- demo server; the project page reads this URL from here too -->
  <meta name="ovh-demo-server" content="{server_url}">
  <link rel="preconnect" href="{server_url}">
{head_links}
  <link rel="stylesheet" href="static/css/style.css?v={css_version}">
  {theme_script}
</head>
<body>
{sprite}
{nav}
<main id="top">
{demo}
</main>
{lightbox}
<script src="static/js/examples.js?v={versions['examples']}"></script>
<script type="module" src="static/js/demo.js?v={versions['demo']}"></script>
{EXTRA_SCRIPT}
</body>
</html>
"""
    out = Path(out)
    if out.exists():
        shutil.rmtree(out)
    (out / "static/js").mkdir(parents=True)
    (out / "index.html").write_text(html)
    (out / "README.md").write_text(README)
    shutil.copytree(ROOT / "static/css", out / "static/css")
    shutil.copytree(ROOT / "static/icons", out / "static/icons")
    for name in ("examples", "demo"):
        shutil.copy(ROOT / f"static/js/{name}.js", out / f"static/js/{name}.js")
    # the demo's samples use each example's input images and its thumbnail
    for example in sorted((ROOT / "static/examples").iterdir()):
        files = sorted(example.glob("input_*")) + sorted(example.glob("thumb.*"))
        if files:
            (out / "static/examples" / example.name).mkdir(parents=True)
            for f in files:
                shutil.copy(f, out / "static/examples" / example.name / f.name)
    return out


if __name__ == "__main__":
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    print(build(sys.argv[1], sys.argv[2]))
